[project]
name = "rag-intent-router"
version = "0.1.0"
description = "MiniLM-based intent router with classical ML models"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Yuvaraj" }
]

dependencies = [
  "sentence-transformers",
  "scikit-learn",
  "pandas",
  "numpy",
  "joblib"
]

[tool.setuptools]
package-data = { "rag_intent_router" = ["models/*.joblib"] }

[project.urls]
Homepage = "https://github.com/yuvarajd2588/rag-intent-router"
